export const CREATE_TODOTASK_START = 'CREATE_TODOTASK_START';
export const CREATE_TODOTASK_SUCCESS = 'CREATE_TODOTASK_SUCCESS';
export const CREATE_TODOTASK_FAILED = 'CREATE_TODOTASK_FAILED';

export const UPDATE_TODOTASK_START = 'UPDATE_TODOTASK_START';
export const UPDATE_TODOTASK_SUCCESS = 'UPDATE_TODOTASK_SUCCESS';
export const UPDATE_TODOTASK_FAILED = 'UPDATE_TODOTASK_FAILED';

export const DELETE_TODOTASK_START = 'DELETE_TODOTASK_START';
export const DELETE_TODOTASK_SUCCESS = 'DELETE_TODOTASK_SUCCESS';
export const DELETE_TODOTASK_FAILED = 'DELETE_TODOTASK_FAILED';

export const FETCH_TODOTASK_SUCCESS = 'FETCH_TODOTASK_SUCCESS';
export const FETCH_TODOTASK_FAILED = 'FETCH_TODOTASK_FAILED';

export const PROCESS_FAILURE_CONFIRMED = 'PROCESS_FAILURE_CONFIRMED';